coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 70%
  ignore:
    - "tests/"
    - "src/terminus/__init__.py"
    - "src/terminus/main.py"
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
